name: Build Kernel Poco X3 Pro
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: ./
        with:
          kernel-url: https://github.com/tejas101k/kernel_xiaomi_vayu
          kernel-dir: msm-4.14
          kernel-branch: vayu-14
          config: vayu_user_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
          
